### ISSUE TITLE
Broken in Sketch 48

### ISSUE THREAD

**Issue by benchow** [Arkkimaagi/ArtboardZoom#15]
When I re-installed Sketch 47 it worked again.

Love this plugin btw!

**Comment by Arkkimaagi** [comment]
Oh shoot. So it appears. I will take a look at it as soon as I can.

Thank you for your kind words!

**Comment by Arkkimaagi** [comment]
Could you please check that it works now in Sketch 47 and 48 with the latest plugin 1.2.2? I think I found the culprit in a changed function name from `currentView` to `contentDrawView` in the Sketch API.

**Comment by chrischernoff** [comment]
Confirmed fixed in 48. Thanks so much @Arkkimaagi!
