### ISSUE TITLE
Not working for me in 48.1

### ISSUE THREAD

**Issue by Pxlfist** [Arkkimaagi/ArtboardZoom#16]
I updated the plugin but can't get it working for 48.1

I didn't realize how much I used it and relied on your plugin for quick navigation until it ceased working. So thank you for it.

**Comment by Arkkimaagi** [comment]
Could you check that you have really the latest version? It should work.

**Comment by Pxlfist** [comment]
Sorry about that: Sketchpacks kept telling me I had successfully updated, but then when I later clicked the 'Managed' tab, it revealed it was using the old version still. It did this multiple times, realized it was not going to update via that tool and then I just manually deleted the original files and grabbed the latest directly from GitHub.

All is well now. Thanks again for the great plugin.
