### ISSUE TITLE
Running plugin causes Sketch to crash in version 3.3 released today.

### ISSUE THREAD

**Issue by Octal40** [Arkkimaagi/ArtboardZoom#4]
I love this plugin and use it constantly, but it crashes with 3.3. It looks like it's trying to zoom out way too far and Sketch becomes unresponsive. Have to force quit the app.

**Comment by davidpanzarella** [comment]
Same here.

**Comment by Augus** [comment]
Same here.

**Comment by mistermanix** [comment]
Same here.

**Comment by mischugo** [comment]
Same here

**Comment by jslvtr** [comment]
Fixed with #6 (if it gets pulled).

**Comment by zhe** [comment]
Same here. Waiting to merge the fix.

**Comment by Arkkimaagi** [comment]
Sorry about this, I was not using Sketch and just now found this same issue. To add to the problem for some reason I got no notification about these issues in the github. I wonder why.

You have my sincerest apologies.

**Comment by Arkkimaagi** [comment]
Closing this as I have now merged the pull request
