### ISSUE TITLE
Currently crashing for me...

### ISSUE THREAD

**Issue by kmh808** [Arkkimaagi/ArtboardZoom#5]
Hi,  This plugin is crashing Sketch on me.  I'm on Sketch 3.3 running OSX 10.9.5 on a 2014 MacBook Pro.

**Comment by jslvtr** [comment]
I have the same problem, Sketch 3.3.1 on OSX 10.10.1, on a Mid-2012 MacBook Pro.

**Comment by justdan0227** [comment]
Still not working :(

**Comment by Arkkimaagi** [comment]
Sorry about this, I missed this myself and did not get a notification about these reports.

**Comment by kmh808** [comment]
Just out of curiosity, was it fixed? 

Thanks, 
Kevin

**Comment by jslvtr** [comment]
Yes, it was, with #6

**Comment by Arkkimaagi** [comment]
Yep, I merged the commit from @jslvtr, thanks again. :)

**Comment by justdan0227** [comment]
Appears to be working now!  Thanks!

**Comment by kmh808** [comment]
Awesome sauce.  Thanks!
