### ISSUE TITLE
Sketch Toolbox is still using the first release

### ISSUE THREAD

**Issue by benklocek** [Arkkimaagi/ArtboardZoom#7]
Not sure how you submit a package to Sketch Toolbox, but it's installing the initial release instead of these updates for Sketch 3.3.

**Comment by Arkkimaagi** [comment]
Hmm, that's weird. When I install using Sketch Toolbox, I do get the latest 1.0.1 version. Maybe there is something wrong with your install of Sketch Toolbox?

**Comment by benklocek** [comment]
Thanks for the suggestion. Glad it's just a local issue. Now to figure out how to clean my install?

**Comment by Arkkimaagi** [comment]
Did you get it fixed?

**Comment by benklocek** [comment]
I just updated things manually. Haven't had time to dig deep. Thanks for checking back.
