### ISSUE TITLE
Feature request: auto 100%

### ISSUE THREAD

**Issue by xzab** [Arkkimaagi/ArtboardZoom#8]
After hitting cmd+4, can you have it auto zoom to 100% so we don't have to then hit cmd+0?  Also, it may be nice to have a feature where we can designate this to replace cmd+0 so by default cmd+0 automatically zooms to 100% based on which artboard is selected. 

Other than those ideas, this is awesome, nice job and thank you!!

**Comment by xzab** [comment]
I realized there is CMD+3 to achieve centering an artboard, and then CMD+0 to zoom to 100%;  And not the purpose of this plugin.

**Comment by Arkkimaagi** [comment]
I actually tried to have this feature in the first version of this plugin. Sketch did not however behave nicely with these two commands together, but instead zoomed or focused on wrong part of screen. You can actually experience this when doing these zooms by shortcuts even now.

For my screen size and the iPhone retina size screens the automatic 100% would work perfectly, but I'd imagine that it would not work as well if I'd work on bigger artboards on a smaller screen. So maybe it's better to have these shortcuts.

Anyways, thank you for your kind words. It's an easy enough plugin to maintain and people have helped me with it. If you have more suggestions how to improve it, let me know. :)

**Comment by toorshia** [comment]
I've been researching for last 2 hours on how to trigger zoom to 100% from plugin and was unable to find it. Can you share your code from first version? I would like to try it out, perhaps it works better with current version of Sketch. Thanks

**Comment by Arkkimaagi** [comment]
I did not find my initial version, but I did found a snippet for handling zoom levels.

Maybe this bit helps you in your quest.

```javascript
  var doc = context.document;
  var zoom = doc.zoomValue()*100;
  doc.showMessage("Current zoom level: "+zoom+"%");
  doc.zoomValue=1; // Change zoom level to 100%;
```

Please do share what you end up with. :)

**Comment by toorshia** [comment]
No luck, bro :) It's not working + produces some weird bounding boxes (until I manually zoom in or out).

**Comment by Arkkimaagi** [comment]
I think there was a way to make it redraw the view, just can not remember what it was.

**Comment by toorshia** [comment]
There's also [view actualSize] but that's not doing the trick either.

**Comment by Arkkimaagi** [comment]
I have a couple of ideas, let me get back to this in a few hours

**Comment by toorshia** [comment]
Solved (kind of) :)
https://github.com/frankko/Artboard-Tools/issues/5

**Comment by Arkkimaagi** [comment]
I decided to add support for this once for all. Now ArtboardZoom 1.2.0 supports zooming to 100% when the shortcut <kbd>⌘</kbd> + <kbd>⌥</kbd> + <kbd>4</kbd> is typed
