### ISSUE TITLE
Support for new Sketch 3.4 plugin feature

### ISSUE THREAD

**Issue by katywebster** [Arkkimaagi/ArtboardZoom#9]
Hi,

Love your plug-in, use it constantly! However, Sketch 3.4 has introduced a new plugin feature which is different from before. I believe you need to do "something" in order for your plugin to work with the new feature - http://www.sketchapp.com/support/documentation/13-preferences/4-plugins.html

Thanks in advance,
Katy

**Comment by Arkkimaagi** [comment]
Thanks for this, I came here after I figured out that I indeed have to do something to get it working again.

I'll try to sort it out asap. If there are any instructions on what to do, let me know. :)

**Comment by katywebster** [comment]
Hi,
I've had a look on the Sketch 3 site but I'm not a developer so I'm afraid I won't be much help! 
Thanks,
Katy

**Comment by Arkkimaagi** [comment]
I have now updated the plugin to support the new 3.4 plugin format. I also updated the zoom to leave a little padding around the artboard.
